server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HZ
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

feign: #通过配置文件来自定义Feign的配置
  client:
    config:
      default: #这里用default就是全局配置，如果写某个服务名称，则是针对某个微服务的配置
        loggerLevel: NONE #日志级别
  httpclient: #httpclient的配置
    enabled: true
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka